# fly.toml app configuration file generated for r-sum-2024 on 2024-11-13T23:33:40-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'r-sum-2024'
primary_region = 'ord'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

  [build]
  builder = "heroku/buildpacks:20"

[[services]]
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
